apiVersion: v1
kind: ConfigMap
metadata:
  name: twc-recommendations-config
  namespace: recommendations
data:
  CLICKHOUSE_HOST: "mkiam5ktvm.ap-southeast-2.aws.clickhouse.cloud"
  CLICKHOUSE_PORT: "8443"
  CLICKHOUSE_DATABASE: "default"
  CLICKHOUSE_SECURE: "true"
  CLICKHOUSE_USER: "default"
  LOG_LEVEL: "INFO"